workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - verify

verify:
  stage: verify
  image: python:3.9
  tags:
    - gsp-privileged
  before_script:
    - apt-get update && apt-get install --no-install-recommends -y make
    - make ci-install
  script:
    - make test
